### ISSUE TITLE
camera/color topic returns black and white images

### ISSUE THREAD

**Issue by moutalibbadr** [turtlebot/turtlebot4_simulator#12]
- OS: (e.g. Ubuntu 20.04)
 - ROS Distro: (e.g. Galactic)
 - Built from source 
 - Package version: galactic

 **Expected behaviour**
 camera/color topic to return images in rgb.

 **Actual behaviour**
although the encoding is rgb8 the image pixel values seem to be between 255-255-255 and 0-0-0 which gives a black and white image.

**To Reproduce**
ros2 launch turtlebot4_ignition_bringup ignition.launch.py rviz:=true 
add camera/color topic in rviz 

**Other notes**
I can't say for sure if this is due to ignition or the camera definition in the urdf.

**Comment by moutalibbadr** [comment]
Here is an illustration of this issue. 
![Screenshot](https://user-images.githubusercontent.com/50052549/162154769-70f11dce-cd09-4a93-ac99-1f45fafc6636.png)

**Comment by roni-kreinin** [comment]
If you change the render engine to ogre2 here https://github.com/iRobotEducation/create3_sim/blob/main/irobot_create_common/irobot_create_description/urdf/create3.urdf.xacro#:~:text=%3Crender_engine%3Eogre%3C/render_engine%3E, the image should publish correctly. Expect worse performance though.

Side note: If you pull the latest turtlebot4_description it will fix the red models that you are seeing in RVIZ

**Comment by moutalibbadr** [comment]
Thank you this solved the issue. And thank you for the tip on the red models.
