### ISSUE TITLE
ACML issues

### ISSUE THREAD

**Issue by ahcorde** [turtlebot/turtlebot4_simulator#14]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: e.g. Galactic
 - Built from source

 **Expected behaviour**

Run `amcl_core` without issues. This might be a nav2 issue.

 **Actual behaviour**

I'm getting this error:

```bash
[amcl-37] /opt/ros/galactic/lib/nav2_amcl/amcl: symbol lookup error: /opt/ros/galactic/lib/libamcl_core.so: undefined symbol: _ZN9nav2_amcl20LikelihoodFieldModelC1EddddmP5map_t
```

**To Reproduce**
Provide the steps to reproduce:

 ```
reset && ros2 launch turtlebot4_ignition_bringup ignition.launch.py slam:=sync rviz:=true localization:=true
```

**Other notes**

I compiled `nav2_acml` and I'm not getting this error. But I'm not able to set the initial position and navigate through the map. I can see this error:

```bash
[rviz2-15] [ERROR] [1651093133.026960494] [rviz2]: navigate_to_pose action server is not available. Is the initial pose set?
````

![tb4_slam](https://user-images.githubusercontent.com/1933907/165630055-c5204a37-22d3-4ad6-92a0-c343eaf5f63b.gif)

As you can see in this gif, I can't see the ACML particles when I set the initial pose. This means that we can't navigate too.

**Comment by roni-kreinin** [comment]
Looking into it. I would recommend for now just using SLAM and nav2 together, without localization.

**Comment by roni-kreinin** [comment]
Found the issue. The Nav2 AMCL package uses a `sensors_lib` library which is the same name as the sensors library built by `irobot_create_ignition_toolbox`. I am making a PR to change that library name.

**Comment by roni-kreinin** [comment]
See https://github.com/iRobotEducation/create3_sim/pull/178

**Comment by roni-kreinin** [comment]
Closing as the error has been fixed.
