### ISSUE TITLE
RGB image is incorrect

### ISSUE THREAD

**Issue by atinfinity** [turtlebot/turtlebot4_simulator#15]
**Please provide the following information:**
 - OS: Ubuntu 20.04 64bit
 - ROS Distro: Galactic
 - Built from source or installed: installed turtlebot4 packages via apt
 - Package version: 0.1.0

 **Expected behaviour**

ROS2 user can subscribe RGB image from Ignition Gazebo.
 
 **Actual behaviour**

I displayed RGB image(`/color/image`) using rqt_image_view.  
But, it seems that RGB image is incorrect.

![Screenshot from 2022-05-09 21-49-22](https://user-images.githubusercontent.com/2630323/167415017-948dc2ee-bef8-4db0-a0e9-25d25cdd6d7d.png)

**To Reproduce**

### 1. install packages

```shell
sudo apt install ros-galactic-turtlebot4-*
sudo apt install ros-galactic-irobot-create-nodes
```

### 2. launch turtlebot4_ignition_bringup

```shell
ros2 launch turtlebot4_ignition_bringup ignition.launch.py
```

### 3. launch rqt_image_view

```shell
ros2 run rqt_image_view rqt_image_view
```

**Comment by atinfinity** [comment]
Sorry. This report duplicate with <https://github.com/turtlebot/turtlebot4_simulator/issues/12>. So, I closed this issue.
I changed to `ogre2` with reference to <https://github.com/turtlebot/turtlebot4_simulator/issues/12#issuecomment-1091736349>. As a result, RGB image published correctly.

![Screenshot from 2022-05-09 22-28-55](https://user-images.githubusercontent.com/2630323/167420578-f6a6e7e0-3fa8-48a1-8d12-57e4dee11a0d.png)

And, I checked publish rate using `ros2 topic hz`. But, publish rate is very slow(about 5Hz). 
Do you have a plan to improve this problem?

**Comment by roni-kreinin** [comment]
The reason I used the `ogre` render engine is because `ogre2` provides poor performance. I am not sure if there is a good way to optimize it at the moment other than reducing the image resolution further. Ignition Edifice has reached end-of-life, so this will likely remain the same until Humble and Fortress are supported for the TurtleBot 4.
