### ISSUE TITLE
Bot not moving inside rviz for different world apart from depot 

### ISSUE THREAD

**Issue by Srimathi-tw** [turtlebot/turtlebot4_simulator#21]
**Please provide the following information:**
 - OS: Ubuntu 20.04
 - ROS Distro: Galactic
 - Built from source or installed: Source
 - Package version: Latest (irobot_create_msgs - galactic branch rest all from dependencies)

 **Expected behaviour**
On running
```ros2 launch turtlebot4_ignition_bringup ignition.launch.py model:=lite rviz:=true slam:=sync world:=maze```
and moving the bot around we should able to move it around in gazebo and the same should be reflected in rviz as well

 **Actual behaviour**
We are able to move it around in gazebo but in rviz it is struck at the same dock for worlds apart from depot

**To Reproduce**

1. Run ```ros2 launch turtlebot4_ignition_bringup ignition.launch.py model:=lite rviz:=true slam:=sync world:=maze```
2. Try driving the bot [ https://turtlebot.github.io/turtlebot4-user-manual/tutorials/driving.html]( https://turtlebot.github.io/turtlebot4-user-manual/tutorials/driving.html ) by following the manual

**Other notes**
We raised an issue #20 for rplidar but after increasing the lidar value vertically it was showing an improved range in depot. But the same was not visible in rviz for worlds apart from depot

In depot after increasing range
![image](https://user-images.githubusercontent.com/103632054/191734403-f6570a23-2c05-4008-9412-5f995b7dfa31.png)
In maze after increasing range
![image](https://user-images.githubusercontent.com/103632054/191735268-1dfe6f4c-beee-421a-aa2a-338704b168bf.png)

**Comment by roni-kreinin** [comment]
I am seeing a similar issue with the maze world. It seems that the laserscan is not being published on the ROS side of the bridge, which causes SLAM to not create a map. If you switch the fixed frame under 'Global Options' to `odom` then you should still see the robot move around.

I will look into the maze world as it does need some reworking. For now I will recommend using depot.

**Comment by Srimathi-tw** [comment]
We are also experiencing the same behavior as mentioned above and thanks for the workaround we are now able to move it around in rviz but not able to see lidar values as mentioned above

**Comment by harishkumarb-tw** [comment]
@roni-kreinin The problem is that the laser scan and other sensor data have incorrect topic remapping between ros2 and ign topics. The current Implementation takes the world name from the SDF file inside <world name=> tag and uses it in the topic name.

I resolved it by editing the world/sdf file to the name which is used to call the world launch parameter **world:=** (Name of the custom world/sdf file).

Now, the topic remapping is proper and the ign data is getting published on ros2 topics.
