### ISSUE TITLE
Turtlebot 4 simulator not compiling from source

### ISSUE THREAD

**Issue by jefflsilveira** [turtlebot/turtlebot4_simulator#24]
**Please provide the following information:**
 - OS: Description:	Ubuntu 20.04.5 LTS
 - ROS Distro: Galactic
 - Built from source or installed: from source
 - Package version: [c63ffdc](https://github.com/turtlebot/turtlebot4_simulator/commit/c63ffdc420881d6870b49f98f9ed1715b8645f35)

 **Expected behaviour**
I expected to compile the package.

 **Actual behaviour**
This error:
\--- stderr: irobot_create_ignition_toolbox   
/usr/bin/ld: libirobot_create_ignition_sensors_lib.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<irobot_create_msgs::msg::Dock_<std::allocator<void> > >()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sensors_node.dir/build.make:201: sensors_node] Error 1
make[1]: *** [CMakeFiles/Makefile2:223: CMakeFiles/sensors_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
\---
Failed   <<< irobot_create_ignition_toolbox [48.1s, exited with code 2]
Aborted  <<< turtlebot4_node [50.0s]                    
Aborted  <<< irobot_create_nodes [51.4s]                
Aborted  <<< irobot_create_gazebo_plugins [1min 13s]

                                        
Summary: 12 packages finished [1min 46s]
  1 package failed: irobot_create_ignition_toolbox
  3 packages aborted: irobot_create_gazebo_plugins irobot_create_nodes turtlebot4_node
  2 packages had stderr output: irobot_create_ignition_toolbox turtlebot4_node
  7 packages not processed

**To Reproduce**
I followed the steps shown here: https://turtlebot.github.io/turtlebot4-user-manual/software/turtlebot4_packages.html#turtlebot-4-simulator

1 - Not sure if it is relevant, but before trying to install the simulator, I installed the Turblebot 4 and Turtlebot 4 Desktop using apt install and compiled from source the Turtlebot 4 Desktop in the same workspace as the Simulator (turtlebot4_ws).
2 - 
sudo apt-get update && sudo apt-get install wget
sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
--2022-10-25 12:59:54--  http://packages.osrfoundation.org/gazebo.key
sudo apt-get update && sudo apt-get install ignition-edifice

cd ~/turtlebot4_ws/src
git clone https://github.com/turtlebot/turtlebot4_simulator.git
cd ~/turtlebot4_ws
vcs import src < src/turtlebot4_simulator/dependencies.repos
rosdep install --from-path src -yi
source /opt/ros/galactic/setup.bash
colcon build --symlink-install

This is the full output from the last command:
[0.239s] WARNING:colcon.colcon_core.package_selection:Some selected packages are already built in one or more underlay workspaces:
	'irobot_create_msgs' is in: /opt/ros/galactic
	'turtlebot4_description' is in: /opt/ros/galactic
	'turtlebot4_msgs' is in: /opt/ros/galactic
	'turtlebot4_node' is in: /opt/ros/galactic
If a package in a merged underlay workspace is overridden and it installs headers, then all packages in the overlay must sort their include directories by workspace order. Failure to do so may result in build failures or undefined behavior at run time.
If the overridden package is used by another package in any underlay, then the overriding package in the overlay must be API and ABI compatible or undefined behavior at run time may occur.

If you understand the risks and want to override a package anyways, add the following to the command line:
	--allow-overriding irobot_create_msgs turtlebot4_description turtlebot4_msgs turtlebot4_node

This may be promoted to an error in a future release of colcon-override-check.
Starting >>> irobot_create_msgs
Starting >>> irobot_create_description
Starting >>> irobot_create_toolbox
Starting >>> irobot_create_control
Starting >>> irobot_create_ignition_plugins
Starting >>> turtlebot4_msgs
Starting >>> turtlebot4_ignition_gui_plugins
Starting >>> turtlebot4_navigation
Finished <<< irobot_create_control [0.85s]                              
Finished <<< irobot_create_description [0.98s]                          
Starting >>> turtlebot4_description
Finished <<< turtlebot4_navigation [1.44s]                              
Finished <<< turtlebot4_description [1.11s]                             
Starting >>> turtlebot4_viz
Finished <<< turtlebot4_viz [0.23s]                                     
Starting >>> turtlebot4_desktop
Finished <<< turtlebot4_desktop [0.48s]                                    
Finished <<< irobot_create_toolbox [4.69s]                                 
Finished <<< turtlebot4_msgs [5.78s]                                       
Starting >>> turtlebot4_ignition_toolbox                                   
Finished <<< irobot_create_ignition_plugins [9.87s]                          
Finished <<< turtlebot4_ignition_gui_plugins [12.4s]                          
Finished <<< turtlebot4_ignition_toolbox [16.5s]                               
Finished <<< irobot_create_msgs [32.7s]                         
Starting >>> irobot_create_nodes
Starting >>> irobot_create_ignition_toolbox
Starting >>> irobot_create_gazebo_plugins
Starting >>> turtlebot4_node
[Processing: irobot_create_gazebo_plugins, irobot_create_ignition_toolbox, irobot_create_nodes, turtlebot4_node]
\--- stderr: irobot_create_ignition_toolbox   
/usr/bin/ld: libirobot_create_ignition_sensors_lib.so: undefined reference to `rosidl_message_type_support_t const* rosidl_typesupport_cpp::get_message_type_support_handle<irobot_create_msgs::msg::Dock_<std::allocator<void> > >()'
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/sensors_node.dir/build.make:201: sensors_node] Error 1
make[1]: *** [CMakeFiles/Makefile2:223: CMakeFiles/sensors_node.dir/all] Error 2
make: *** [Makefile:141: all] Error 2
\---
Failed   <<< irobot_create_ignition_toolbox [48.1s, exited with code 2]
Aborted  <<< turtlebot4_node [50.0s]                    
Aborted  <<< irobot_create_nodes [51.4s]                
Aborted  <<< irobot_create_gazebo_plugins [1min 13s]
                                        
Summary: 12 packages finished [1min 46s]
  1 package failed: irobot_create_ignition_toolbox
  3 packages aborted: irobot_create_gazebo_plugins irobot_create_nodes turtlebot4_node
  2 packages had stderr output: irobot_create_ignition_toolbox turtlebot4_node
  7 packages not processed

**Comment by roni-kreinin** [comment]
The `irobot_create_msgs` main branch is now Humble based and not compatible with galactic. You will need to checkout the galactic branch.
