### ISSUE TITLE
SuppressWarning.hh missing

### ISSUE THREAD

**Issue by zenas91** [turtlebot/turtlebot4_simulator#41]
- OS: Ubuntu 22.04
- ROS Distro: Humble
 - Built from source or installed: Built from source
 - Package version:  1.0.0

** Expected behaviour
Successful build with colcon to install

 **Actual behaviour**

Missing File Error
`
--- stderr: turtlebot4_ignition_gui_plugins                             
In file included from /usr/include/ignition/plugin1/gz/plugin/Register.hh:22,
                 from /usr/include/ignition/plugin1/ignition/plugin/Register.hh:18,
                 from /home/zenas/turtlebot4_ws/src/turtlebot4_simulator/turtlebot4_ignition_gui_plugins/Turtlebot4Hmi/Turtlebot4Hmi.cc:26:
/usr/include/ignition/plugin1/gz/plugin/detail/Register.hh:28:10: fatal error: gz/utilities/SuppressWarning.hh: No such file or directory
   28 | #include <gz/utilities/SuppressWarning.hh>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [Turtlebot4Hmi/CMakeFiles/Turtlebot4Hmi.dir/build.make:99: Turtlebot4Hmi/CMakeFiles/Turtlebot4Hmi.dir/Turtlebot4Hmi.cc.o] Error 1
gmake[1]: *** [CMakeFiles/Makefile2:153: Turtlebot4Hmi/CMakeFiles/Turtlebot4Hmi.dir/all] Error 2
gmake: *** [Makefile:146: all] Error 2
---
Failed   <<< turtlebot4_ignition_gui_plugins [1.13s, exited with code 2]

Summary: 1 package finished [1.36s]
  1 package failed: turtlebot4_ignition_gui_plugins
  1 package had stderr output: turtlebot4_ignition_gui_plugins
  2 packages not processed
`

**To Reproduce**
Tried installing the package using the source installation steps provided in [here](https://turtlebot.github.io/turtlebot4-user-manual/software/turtlebot4_simulator.html)

**Other notes**
Both Gazebo and Turtlebot4 are installed successfully and working, only this simulation environment is producing an error.

**Comment by roni-kreinin** [comment]
You might be missing some packages. Did you run `rosdep install --from-path src -yi`?

**Comment by zenas91** [comment]
Yes, I did

**Comment by zenas91** [comment]
It's now working. For some reason it started working after switching to [this](https://turtlebot.github.io/turtlebot4-user-manual/software/turtlebot4_common.html). Maybe specifying the ros distro when running rosdep helped. I can't say for sure.
