### ISSUE TITLE
Turtlebot in world file

### ISSUE THREAD

**Issue by xkaraman** [turtlebot/turtlebot4_simulator#45]
As you can see here, there is a reference to a turtle bot model within the world file. None of the other world files include one, and my guess is because spawning the tb4 is handled separately.

https://github.com/turtlebot/turtlebot4_simulator/blob/c27f15d4e0c612efb799ac81e398137c5f9b154c/turtlebot4_ignition_bringup/worlds/turtlebot4_world.sdf#LL52C1-L58C19

Moreover launching `ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py world:=turtlebot4_world` fails to load the gazebo simulation (fortress) with the error 
```
[Err] [Server.cc:139] Error Code 13: sdf/world[@name="default"]/include[0]/uri:/home/ws/install/turtlebot4_ignition_bringup/share/turtlebot4_ignition_bringup/worlds/turtlebot4_world.sdf:L55]: Msg: Unable to find uri[model://turtlebot4]
```
All other worlds, maze, depot, and warehouse load successfully.

**Comment by hilary-luo** [comment]
Thanks for reaching out. The turtlebot4_world file is outdated and should have been removed. I have noted to make sure it is removed in the next update.
