### ISSUE TITLE
TFs not publishing when using namespace in simulation ROS2-humble 

### ISSUE THREAD

**Issue by y2d2** [turtlebot/turtlebot4_simulator#48]
**Please provide the following information:**
 - OS: Ubuntu22.04
 - ROS Distro: Humble
 - Built from source or installed: Installed. 
 - Package version: Version: 1.0.0-1jammy.20230626.191243 (ros-humble-turtlebot4-simulator)
 - *Build in a docker (I can share the Dockerfile if needed, but I think it is unrelated to running in a docker.)*

 **Expected behaviour**
When I launch: 
`ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py nav2:=true slam:=false localization:=true rviz:=true`
and start the simulation everything works fine and I can use any tutorial node, subsequently when I run the 
`ros2 run tf2_tools view_frames` 
I get i nice big TF tree as expected. 
[tf_frames_no_namespace.pdf](https://github.com/turtlebot/turtlebot4_simulator/files/12121595/tf_frames_no_namespace.pdf)

 **Actual behaviour**
However when I  add a namespace as described in the manual https://turtlebot.github.io/turtlebot4-user-manual/tutorials/multiple_robots.html : 
`ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py namespace:=/robot1 nav2:=true slam:=false localization:=true rviz:=true`
and run the simulation I cannot run the tutorial nodes anymore (using the correct namespace.) Looking at the nodes 
`ros2 topic list` 
Everything looks good, with the right namespaces. However, running: 
`ros2 run tf2_tools view_frames` 
Does not show anything 
[tf_frames_namespace.pdf](https://github.com/turtlebot/turtlebot4_simulator/files/12121608/tf_frames_namespace.pdf)
Although I would expect this command to show all tfs. I also tried it with: 
` ros2 run tf2_tools view_frames --ros-args -r __ns:=/robot1` 
With similar result.

I am not sure If I overlooked anything.

**To Reproduce**
Terminal 1:  (Source to ros install setup.bash)
`ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py namespace:=/robot1 nav2:=true slam:=false localization:=true rviz:=true`
Terminal 2: (Source to ros install setup.bash)
`ros2 run tf2_tools view_frames` 

Should create a pdf with no frames.

**Comment by hilary-luo** [comment]
Hello, in order to view the namespaced frames using the tf2_tools package, try the following command:
```
ros2 run tf2_tools view_frames --ros-args -r __ns:=/robot1 -r /tf:=tf -r /tf_static:=tf_static
```

If this fixes your issue please close the ticket, if not please share additional information about any remaining issues.

**Comment by y2d2** [comment]
Hi! 

Yes this command actually shows the tf tree I was expecting.  However, it seems I can still not perform any Python tutorials when using the namespace. 

Should I continue here or create another issue? 

**Expected behaviour**
When I launch the simulation without namespacing:
`ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py nav2:=true slam:=false localization:=true rviz:=true`
And start it and run, for example, the patrol_loop node: 
`ros2 run turtlebot4_python_tutorials patrol_loop`
It works as expected. 

**Actual behaviour**
When I add the namespacing: 
`ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py namespace:=/robot1 nav2:=true slam:=false localization:=true rviz:=true`
Start the simulation and run 
`ros2 run turtlebot4_python_tutorials patrol_loop --ros-args -r __ns:=/robot1`  
Does not work.

**Possible Issue** 
Now that I could have a look at the TF tree I noticed the TF from /robot1/odom to /robot1/base-link is missing:
![image](https://github.com/turtlebot/turtlebot4_simulator/assets/10230591/169acaa6-bb24-49d6-b928-e554cb19c9fc)
Maybe that is causing the navigation stack to malfunction?  (Likely since there is no link now between the odom and the lidar?) 

Morever it seems to be 2 base_links now, one with the namespace and one without. 

However, I am not sure how to fix it. I suppose just broadcasting a transformation is wrong since this transformation should come from the navigation stack.  

Cheers, 

Yuri

**Comment by hilary-luo** [comment]
Hi Yuri, 

There seems to be an issue with how the namespace is passed through. In the meantime as a work around, can you try launching nav and localization in their own terminals and remove the `/` from the beginning of the namespace as shown below:
`ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py namespace:=robot1 rviz:=true`
`ros2 launch turtlebot4_navigation nav2.launch.py namespace:=robot1`
`ros2 launch turtlebot4_navigation localization.launch.py namespace:=robot1`

Then go ahead and launch the tutorial as you had indicated
`ros2 run turtlebot4_python_tutorials patrol_loop --ros-args -r __ns:=/robot1`

**Comment by y2d2** [comment]
Hi, 

I tried this, but the result is the same. The TF tree is disconnected between the robot1/odom and robot1/base_link 
The nav2.launch.py actually gives this now as a visible error: 
`[controller_server-1] [INFO] [1690360403.166904785] [robot1.local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.`

So I assume the issue is within the launch file of the turtlebot4_ignition.launch . 

Cheers, 

Yuri

**Comment by hilary-luo** [comment]
Hi Yuri, 

Are you pressing play on gazebo? I expect for odom to be disconnected until the system launches completely (following pressing play). I am unable to replicate the issue you are seeing.

Please run `ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py namespace:=robot1`, press play in gazebo and give it a second, then check the tf tree and share the full terminal output.

**Comment by y2d2** [comment]
Hi! 
I apologize must have forgotten to start the simulation since the work around works now.
Thanks for the support! 

Cheers, 

Yuri

**Comment by y2d2** [comment]
Hi!
I apologize must have forgotten to start the simulation since the work around works now.
Thanks for the support!

Cheers,

Yuri

**Comment by dkavroulakis** [comment]
Hello, I have exactly the same issue with y2d2 and I did everything you mentioned above, but the issue still exists. I would like to visualize the turtlebot4 lite in a web interface and I am using this project: https://github.com/MoffKalast/vizanti/tree/ros2 because I can't visualize it using rviz web in ROS2. When I use namespace the map doesn't show up in the vizanti project, but when I remove the namespace the map shows up. How could I solve this issue ?

**Comment by hilary-luo** [comment]
@dkavroulakis The turtlebot TF is namespaced. You will need to either reach out on that project for support on how to launch the visualizer for a namespaced TF or republish the TF from the namespaced topic to a non-namespaced topic.
