### ISSUE TITLE
unable to map new obstacles and track new path

### ISSUE THREAD

**Issue by ghost** [turtlebot/turtlebot4_simulator#50]
working on turtlebot4_ignition_bringup
`ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py nav2:=true slam:=false localization:=true rviz:=true world:=maze map:=src/turtlebot4/turtlebot4_navigation/maps/maze.yaml `
When I added a new obstacle manually from ignition.When updating theobstacle is in the way of turtlebot4. turtlebot4 is not updating its path. It is colliding the obstacle. how to make turtlebot4 detect obstacle and trace a new path
[Screencast from 08-18-2023 03:02:01 PM.webm](https://github.com/turtlebot/turtlebot4_simulator/assets/51513859/36bae115-1904-4888-8868-2c1310d37372)

**Comment by hilary-luo** [comment]
@vamsi1961 Every time you enter a Turtlebot4 issue please use the provided templates and fill in the following information:

OS: (e.g. Ubuntu 20.04)
ROS Distro: (e.g. Galactic)
Built from source or installed:
Package version: (if from repository, give version from sudo dpkg -s ros-$ROS_VERSION-turtlebot4-PACKAGE_WITH_ISSUE, if from source, give commit hash)

This will assign someone to your issue and ensure the fastest possible response. 

Looking at the obstacle that you dropped into the world, it seems transparent. Can you use the visualize lidar plugin in gazebo and verify that the lidar rays do not go through the obstacle? If so then you need to include a different type of obstacle.

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
