### ISSUE TITLE
Gazebo world not loading properly in Galactic

### ISSUE THREAD

**Issue by teufelweich** [turtlebot/turtlebot4_simulator#52]
Using the following versions of ROS, Gazebo, and Ubuntu:

    ROS: Galactic
    Gazebo: Ignition-Edifice
    Ubuntu: 20.04

After Gazebo installing with [this guideline](https://turtlebot.github.io/turtlebot4-user-manual/software/turtlebot4_simulator.html#installation) I followed [this tutorial](https://turtlebot.github.io/turtlebot4-user-manual/software/simulation.html) to simulate the TB4 and here's what i get: 
![image](https://github.com/turtlebot/turtlebot4_simulator/assets/33784413/b17f8db3-a04e-40a0-be83-94aa8cd498ec)

The computer has some issues with the GUI and can't show the simulation world properly.
This is the log file: [gazebo_logs.txt](https://github.com/turtlebot/turtlebot4_simulator/files/12715802/gazebo_logs.txt)

I also tried [this tutorial](https://docs.ros.org/en/galactic/Tutorials/Advanced/Simulators/Ignition.html), which worked better. But the simulation world wasn't completely displayed, but I was able to drive the robot with the keyboard. There seems to be an underlying issue with the simulator, I guess.
![image](https://github.com/turtlebot/turtlebot4_simulator/assets/33784413/65a6a6a3-2558-4411-b600-658c0ccabdc0)

**Comment by hilary-luo** [comment]
Great question! Unfortunately this doesn't sound like it is an issue specific to the turtlebot and therefore this isn't the best place for the question. Our team has a wealth of experience with our products but we aren't going to be the best people to troubleshoot a gazebo issue such as this. You can reach out to the to the ROS community on stack exchange, (https://robotics.stackexchange.com/). There are plenty of very helpful ROS and Gazebo experts there. Best of luck!
