### ISSUE TITLE
Weird behaviour on simulation

### ISSUE THREAD

**Issue by FranciscoGomez90** [turtlebot/turtlebot4_simulator#64]
### Understand?
Yes

I followed the tutorial on simulation turtlebot4 on ignition gazebo. I am able to install the packages, no problem. However, when I try to run the simulation with the command 
`ros2 launch turtlebot4_ignition_bringup ignition.launch.py`
And a weird plane appears on the simulator and the RVIZ reports a lot of problems.

I just uploaded a screen cap of the issue

![Captura de pantalla de 2024-01-24 11-21-06](https://github.com/turtlebot/turtlebot4_simulator/assets/16671748/0df5c46a-43bc-499c-bf0a-dd067d26796f)

Any clues of whats happening and how can I solve it??

thanks!

**Comment by hilary-luo** [comment]
@FranciscoGomez90 As requested in this description of the "troubleshooting issue":
> If you need troubleshooting help please use the troubleshooting form from the Turtlebot4 repo: https://github.com/turtlebot/turtlebot4/issues/new/choose.

There it will prompt you to indicate all of the information that is needed for us to assist you with this issue. It will also prompt you for the terminal output which is necessary to understand what you are seeing.
