### ISSUE TITLE
What is the moving distance of tb4 when undocked by pressing the button in docked state?

### ISSUE THREAD

**Issue by gustn6591** [turtlebot/turtlebot4_simulator#66]
I want to know the distance turtlebot4 moves from docked state to undocked state.

**Comment by RustyCPR** [comment]
Hi @gustn6591 
Apologies for the late reply. Its about 6" 

The TB4 sticks out 13" from the base charger. 
![image](https://github.com/turtlebot/turtlebot4_simulator/assets/83372407/43fe19a2-6530-48bc-a87b-f12736b6fc35)

When undocked it backs up and rotates to 19" 
 
![image](https://github.com/turtlebot/turtlebot4_simulator/assets/83372407/f72c41da-dbad-414b-90eb-dcb9a8b56ef5)


Test measurement set up for this: 
![image](https://github.com/turtlebot/turtlebot4_simulator/assets/83372407/fcd7fb6c-1e05-4ea2-8dda-4a704a26bd4d)

Best regards,
Rusty

**Comment by gustn6591** [comment]
Thank you!! I will check too
