### ISSUE TITLE
localization:=true does not work, errors

### ISSUE THREAD

**Issue by timmarkhuff** [turtlebot/turtlebot4_simulator#75]
### Robot Model

Turtlebot4 Lite

### ROS distro

Humble

### Networking Configuration

I do not know

### OS

Ubuntu 22.04

### Built from source or installed?

Installed

### Package version

`dpkg -s ros-humble-turtlebot4-simulator`
Package: ros-humble-turtlebot4-simulator
Status: install ok installed
Priority: optional
Section: misc
Installed-Size: 41
Maintainer: rkreinin <rkreinin@clearpathrobotics.com>
Architecture: amd64
Version: 1.0.2-1jammy.20240415.175517
Depends: ros-humble-turtlebot4-ignition-bringup, ros-humble-turtlebot4-ignition-gui-plugins, ros-humble-turtlebot4-ignition-toolbox, ros-humble-ros-workspace
Description: TODO: Package description

### Expected behaviour

Launching with localization:=true does not work; it floods the console with errors. Even when these errors are present, localization seems to work okay, although it is not remarkably accurate and it tends to lose orientation. 

It's unclear what the localization:=true even means. There is also a slam argument. Is that different? Should slam and localization be used together? Should they not be used together? There needs to be better documentation and error handling with these arguments.

I like localization:=true because it loads a full map of the warehouse at launch; I haven't found any other way to do this. However, the errors are distracting. 

### Actual behaviour

I have tried many different combinations of arguments with localization:=true, and they all flood the console with some variation of the following errors. I have found no configuration in which localization:=true works. 

ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py localization:=true
```
[amcl-47] [WARN] [1715363981.669834662] [amcl]: AMCL cannot publish a pose or update the transform. Please set the initial pose...
[amcl-47] [WARN] [1715363983.743022749] [amcl]: AMCL cannot publish a pose or update the transform. Please set the initial pose...
[amcl-47] [WARN] [1715363985.795129378] [amcl]: AMCL cannot publish a pose or update the transform. Please set the initial pose...
```

ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py localization:=true slam:=true
```
[sync_slam_toolbox_node-49] [WARN] [1715363891.195691562] [slam_toolbox]: Failed to compute odom pose
[sync_slam_toolbox_node-49] [WARN] [1715363891.210854090] [slam_toolbox]: Failed to compute odom pose
[sync_slam_toolbox_node-49] [WARN] [1715363891.226011108] [slam_toolbox]: Failed to compute odom pose
[sync_slam_toolbox_node-49] [WARN] [1715363891.244100730] [slam_toolbox]: Failed to compute odom pose
[sync_slam_toolbox_node-49] [WARN] [1715363891.259339848] [slam_toolbox]: Failed to compute odom pose
```

ros2 launch turtlebot4_ignition_bringup turtlebot4_ignition.launch.py slam:=false nav2:=true model:=lite localization:=true
```
[controller_server-45] [INFO] [1715365862.863109649] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.
[controller_server-45] [INFO] [1715365863.363125792] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.
[controller_server-45] [INFO] [1715365863.863131608] [local_costmap.local_costmap]: Timed out waiting for transform from base_link to odom to become available, tf error: Could not find a connection between 'odom' and 'base_link' because they are not part of the same tree.Tf has two or more unconnected trees.
```

### Error messages

```bash
see above
```

### To Reproduce

see above

**Comment by hilary-luo** [comment]
Your output suggests that you have not set your initial pose. Please set your initial pose before trying to do anything else. 

I will also mention that the output that you have shared does not show any errors. This is all expected output based on what you have launched. Please go through the tutorials and read the documentation to understand what each of these parameters do and when you should use them. In particular, I would suggest starting here: https://turtlebot.github.io/turtlebot4-user-manual/tutorials/navigation.html

**Comment by hilary-luo** [comment]
This issue is being closed due to inactivity. If you are still experiencing the issue, feel free to reopen this ticket when you are ready to continue the troubleshooting process.
